CREATE TABLE `user_basic` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT 'id',
  `username` VARCHAR(32) NOT NULL COMMENT '用户名',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `email` VARCHAR(64) NOT NULL COMMENT '邮箱',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户信息';

CREATE TABLE `user_info` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT 'id',
  `name` VARCHAR(64) NOT NULL COMMENT '名字',
  `age` TINYINT(3) UNSIGNED NOT NULL COMMENT '年龄',
  `hobby` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '爱好',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户简介';